name: CICD
on:
  push:
    branches:
      - main

env:
  # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_REGION: ${{ vars.GCP_REGION }}
  GCR_REPOSITORY_NAME: ${{ vars.GCR_REPOSITORY_NAME }}
  IMAGE: nginx
  # DOCKER_HOST: tcp://docker:2375/

jobs:
  push:
    runs-on: ubuntu-latest
    # services:
    #   docker:
    #     image: docker:dind
    #     options: --privileged
    #     ports:
    #       - 2375:2375
    steps:      
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        id: "auth"
        name: 'Authenticate to Google Cloud'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          token_format: access_token

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GOOGLE_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 
          
      - name: 'Docker push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: us-central1-docker.pkg.dev/devops-421112/simplifywoopii-apps/${{ env.IMAGE }}:${{ github.sha }}
          # tags: ${{ env.GOOGLE_REGION }}-docker-pkg.dev/devops-421112/${{ env.GCR_REPOSITORY_NAME }}/${{ env.IMAGE }}:${{ github.sha }}
          

          
    
