name: CICD
on:
  push:
    branches:
      - main

env:
  # GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  GOOGLE_REGION: ${{ vars.GCP_REGION }}
  GCR_REPOSITORY_NAME: ${{ vars.GCR_REPOSITORY_NAME }}
  IMAGE: nginx
  DEMO_HELM_GIT_TOKEN: ${{ secrets.DEMO_HELM_GIT_TOKEN }}
  TARGET_REPOSITORY: ${{ vars.TARGET_REPOSITORY }}
  

jobs:
  push:
    runs-on: ubuntu-latest
    steps:      
      - uses: actions/checkout@v4
      - uses: 'google-github-actions/auth@v2'
        id: "auth"
        name: 'Authenticate to Google Cloud'
        with:
          credentials_json: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
          token_format: access_token

      - name: Login to GAR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GOOGLE_REGION }}-docker.pkg.dev
          username: _json_key
          password: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }} 
          
      - name: 'Docker push'
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.GOOGLE_REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCR_REPOSITORY_NAME }}/${{ env.IMAGE }}:${{ github.sha }}

      
  deploy:
    runs-on: ubuntu-latest
    needs: push
    steps:      
      - uses: actions/checkout@v4
        with:
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ env.DEMO_HELM_GIT_TOKEN }}
      - uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'values.yaml'
          propertyPath: 'image.tag'
          value: ${{ github.sha }}
          message: 'ci: Update image tag to ${{ github.sha }}'
          commitChange: true
          branch: main
          repository: ${{ env.TARGET_REPOSITORY }}
          token: ${{ env.DEMO_HELM_GIT_TOKEN }}
        
    
